#!/bin/bash
sudo apt-get install modemmanager gammu wammu
sudo apt-get install tightvncserver
sudo apt-get install apache2
sudo apt-get install php5 libapache2-mod-php5 php5-curl php5-imap libssh2-php

sudo /etc/init.d/apache2 restart

sudo apt-get install mysql-server
sudo apt-get install libapache2-mod-auth-mysql php5-mysql phpmyadmin

sudo sed -i.bak s/';   extension=msql.so'/'extension=msql.so'/g /etc/php5/apache2/php.ini
sudo /etc/init.d/apache2 restart
if [ ! -f nickysms.tar.gz ]
then
  wget http://dontommy.com/nickysms.tar.gz
fi
if [ ! -d nickysms ]
then
	cd /var/www/
	tar xvf nickysms.tar.gz
fi
if [ ! -d nicky ]
then
	echo "Kontakt Tommy Maersk, Noget er galt!"
fi
echo "Dit MySQL Password:"
read db_pass
sed -i.bak s/DBPASSWORD/$db_pass/g /var/www/config.php
cp /var/www/.gammurc /home/pi/.gammurc
db="CREATE DATABASE sms_db"
mysql -u root -p$db_pass -e "$db"
mysql -u root -p sms_db < /var/www/nickysms/smsdb.sql
sudo echo "startx" >> /etc/profile
echo "You are at the end, its all set up... now go have a brew..."
